CREATE DATABASE IF NOT EXISTS IRC_DB;

USE IRC_DB;

-- Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip-addr VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
);

-- Create MESSAGES table
CREATE TABLE IF NOT EXISTS MESSAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    message TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id) REFERENCES USERS(id),
    FOREIGN KEY (receiver_id) REFERENCES USERS(id)
);

